@include('dashboard.layout.head')
@include('dashboard.layout.sidebar')
@include('dashboard.layout.header')
@include('dashboard.layout.flash')
@yield('content')
@include('dashboard.layout.footer')
@include('dashboard.layout.foot')
